#!/bin/sh
cd /
mount -t proc proc /proc
mount -o remount,rw /
mount -t sysfs sysfs /sys
mount -t tmpfs mdev /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /bin/mdev > /proc/sys/kernel/hotplug
mdev -s
hostname $(cat /etc/hostname)

